### ISSUE TITLE
plugins.vidio: streams broken

### ISSUE THREAD

**Issue by BBBABUHS** [LaneSh4d0w/query-streamlink#21]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://vidio.com/live/204-sctv

Unable to open URL: https://vidio.com/live/204-sctv (403 Client Error: Forbidden for url: https://www.vidio.com/live/204-sctv)

I think they had fixed but @LaneSh4d0w  didnt update https://github.com/streamlink/streamlink/issues/4640

**Comment by BBBABUHS** [comment]
https://github.com/streamlink/streamlink/pull/4641

**Comment by LaneSh4d0w** [comment]
I've updated my streamlink branch and my query-streamlink services are being updated. Will close this issue once I know everything works.

**Comment by LaneSh4d0w** [comment]
I need to change something in what the code returns.

**Comment by LaneSh4d0w** [comment]
After verification, it seems the servers of Vidio banned the IPs used by free.fullspeed. My implementation works.
