### ISSUE TITLE
Add support for extracting m3u8 from json

### ISSUE THREAD

**Issue by UltraHDR** [LaneSh4d0w/query-streamlink#23]
Add support for extracting m3u8 from json responses such as https://vodapi.mtv.com.lb/api/VODLive/getOneTVLiveStreamLink

**Comment by LaneSh4d0w** [comment]
I could make a plugin that works from the MTV Lebanon link. However, I won't be available tomorrow morning. I'll try looking to it tomorrow afternoon.

**Comment by UltraHDR** [comment]
Thanks take your time. Are you able to make a generic json extension to support roya.com too?

https://ticket.roya.tv/api/livestream/ticket

Thanks

**Comment by Cyanogendark** [comment]
there is an error with Dailymotion, it is not extracting the URL because of changes made by the Dailymotion platform, you can check that @LaneSh4d0w

**Comment by LaneSh4d0w** [comment]
Sounds like it's an IP-lock.

**Comment by Cyanogendark** [comment]
@LaneSh4d0w You can test with Dailymotion, and you can analyze, and another question, which http header supports query-streamlink? And is there possibility to capture m3u8 running on web pages and extract with streamlink?

**Comment by LaneSh4d0w** [comment]
> @LaneSh4d0w You can test with Dailymotion, and you can analyze, and another question, which http header supports query-streamlink? And is there possibility to capture m3u8 running on web pages and extract with streamlink?

I have an "username not found" issue personally on my version. 

In terms of header I haven't worked on anything involving header additions, some plugins may add some headers.

It's the main philosophy behind Streamlink, some difficult stuff can be easily obtained.

**Comment by Cyanogendark** [comment]
Perfect @LaneSh4d0w

**Comment by Cyanogendark** [comment]
@LaneSh4d0w how can i make query-streamlink work in repl.co (replit.com) i have tried but i still can't

**Comment by LaneSh4d0w** [comment]
How do you launch your program ? It may have been locked, since it was banned from usage (on my version).

**Comment by Cyanogendark** [comment]
I already managed to make it work, I have it in different containers

heroku.com
render.com
replit.com
railway.app

I have query-streamlink working on each one, I had to adapt it

**Comment by LaneSh4d0w** [comment]
Since it has changed, I guess we won't need this anymore. In the same pace, I can't make an universal solution, as JSON files change over the different providers. Closing.
