### ISSUE TITLE
Error "Traceback (most recent call last)"

### ISSUE THREAD

**Issue by hellishvictor** [LaneSh4d0w/query-streamlink#24]
Hi, running from Win7 x64 cmd "python main.py" I get this:
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from flask import Flask, request, redirect
ModuleNotFoundError: No module named 'flask'
```
Cheers

**Comment by LaneSh4d0w** [comment]
Have you, by any chance, installed the necessary packages using pip install -r requirements.txt ?

**Comment by hellishvictor** [comment]
I did it right now and I get:

`Collecting git+https://github.com/LaneSh4d0w/streamlink@master (from -r requirements.txt (line 3))
  Cloning https://github.com/LaneSh4d0w/streamlink (to revision master) to c:\windows\temp\pip-req-b
uild-d9azzfrh
  ERROR: Error [WinError 2] El sistema no puede encontrar el archivo especificado while executing co
mmand git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
`

**Comment by LaneSh4d0w** [comment]
Creo que no tienes el programa "Git for Windows". Necesites instalarlo y intenté después un vez mas.

**Comment by LaneSh4d0w** [comment]
Es el mensaje que necesitas tener, eso quiere decir que todo functiona.

**Comment by hellishvictor** [comment]
Ya funciona, muchas gracias y un saludo!

**Comment by LaneSh4d0w** [comment]
Perfecto, me alegra escuchar eso. Saludos.
