### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by dct-infra** [LaneSh4d0w/query-streamlink#6]
Hi there LaneSh4d0w,

I would like to ask if this web app and its deps are installable on a linux VM using pip for example? Is there a howto somewhere? Any guidelines or requirements for VM installations?

Thank you in advance.

**Comment by LaneSh4d0w** [comment]
Hello there.

1) Yes, it's possible if you have Python. Just do pip install -r requirements.txt and then just launch it using python index.py

2) Didn't make one yet, but if the demand is high, i'll get some of my free time to make it.

3) For anything VM related, if your version of query-streamlink is meant for public usage (like mine), get prepared for high heaps of traffic and memory usage. Get at least 2Gb of memory for it, to prevent overheap issues.

**Comment by dct-infra** [comment]
Worked for me!!
Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Now time for the dumb noob question : How to bind to a specific interface:port?

**Comment by LaneSh4d0w** [comment]
> Worked for me!!
> Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
> Now time for the dumb noob question : How to bind to a specific interface:port?

Just look at the end of the index.py code, you can change the port and the rest to your desires.

**Comment by dct-infra** [comment]
`if __name__ == '__main__':
    app.run(threaded=True, host='0.0.0.0', port=5000)`

Thank you very much for the app and for your help!!

**Comment by LaneSh4d0w** [comment]
> `if __name__ == '__main__':
>     app.run(threaded=True, host='0.0.0.0', port=5000)`
> 
> Thank you very much for the app and for your help!!
> 

My pleasure, enjoy !

**Comment by campones** [comment]
I don't see any index.py?  I have updated the port in the main.py file, I run the file but nothing happens

**Comment by BellezaEmporium** [comment]
> I don't see any index.py? I have updated the port in the main.py file, I run the file but nothing happens

I sometimes use index.py for certain platforms (deta, would need to rename main.py to index.py), but now i kept "main.py".
